// =============================================================================
// audio.rs — sound effects and music playback
//
// Every clip is generated by the pure-stdlib Python scripts in tools/ and
// embedded into the binary with include_bytes!, so the game ships as a single
// standalone executable with no asset directory to install alongside it.
//
// This module also owns the throttling that keeps a busy field from turning
// into noise: pops are capped per frame and duck in volume, and the shared
// shoot sound has a minimum gap so a row of Seed Shooters doesn't machine-gun.
// =============================================================================

use macroquad::audio::{load_sound_from_bytes, play_sound, stop_sound, PlaySoundParams, Sound};

/// Music sits well under the effects so it never masks a leak warning.
const MUSIC_VOLUME: f32 = 0.35;
const POP_VOLUME: f32 = 0.55;
const SHOOT_VOLUME: f32 = 0.22;
const SPLASH_VOLUME: f32 = 0.50;
const FREEZE_VOLUME: f32 = 0.35;
const PLACE_VOLUME: f32 = 0.50;
const DENY_VOLUME: f32 = 0.40;
const UPGRADE_VOLUME: f32 = 0.55;
const SELL_VOLUME: f32 = 0.45;
const LEAK_VOLUME: f32 = 0.60;
const WAVE_START_VOLUME: f32 = 0.50;
const WAVE_CLEAR_VOLUME: f32 = 0.55;
const GAME_OVER_VOLUME: f32 = 0.60;

/// Most pop sounds allowed to start in a single frame. A Blender hitting a
/// cluster can pop a dozen fruit at once; playing all of them is a mess.
const MAX_POPS_PER_FRAME: u32 = 3;
/// Each extra pop in the same frame is this much quieter than the last.
const POP_DUCK_PER_EXTRA: f32 = 0.22;
/// Minimum seconds between shoot sounds across every tower on the field.
const SHOOT_MIN_GAP: f32 = 0.055;

/// Which music loop should be playing.
#[derive(Clone, Copy, PartialEq)]
pub enum Track {
    Menu,
    Game,
}

/// All loaded clips plus the throttling state.
pub struct Audio {
    /// Pop clips indexed by fruit tier: 0 = blueberry (highest) … 4 = watermelon.
    pops: Vec<Sound>,
    shoot: Sound,
    splash: Sound,
    freeze: Sound,
    place: Sound,
    deny: Sound,
    upgrade: Sound,
    sell: Sound,
    leak: Sound,
    wave_start: Sound,
    wave_clear: Sound,
    game_over: Sound,
    music_menu: Sound,
    music_game: Sound,

    playing: Option<Track>,
    muted: bool,
    pops_this_frame: u32,
    shoot_cooldown: f32,
}

impl Audio {
    // ─────────────────────────────────────────────────────────────────────────
    // Decode every embedded clip. Called once, before the game loop starts.
    // ─────────────────────────────────────────────────────────────────────────
    pub async fn load() -> Self {
        let mut pops = Vec::with_capacity(5);
        for bytes in [
            include_bytes!("../assets/pop_0.wav").as_slice(),
            include_bytes!("../assets/pop_1.wav").as_slice(),
            include_bytes!("../assets/pop_2.wav").as_slice(),
            include_bytes!("../assets/pop_3.wav").as_slice(),
            include_bytes!("../assets/pop_4.wav").as_slice(),
        ] {
            pops.push(decode(bytes).await);
        }

        Audio {
            pops,
            shoot: decode(include_bytes!("../assets/shoot.wav")).await,
            splash: decode(include_bytes!("../assets/splash.wav")).await,
            freeze: decode(include_bytes!("../assets/freeze.wav")).await,
            place: decode(include_bytes!("../assets/place.wav")).await,
            deny: decode(include_bytes!("../assets/deny.wav")).await,
            upgrade: decode(include_bytes!("../assets/upgrade.wav")).await,
            sell: decode(include_bytes!("../assets/sell.wav")).await,
            leak: decode(include_bytes!("../assets/leak.wav")).await,
            wave_start: decode(include_bytes!("../assets/wave_start.wav")).await,
            wave_clear: decode(include_bytes!("../assets/wave_clear.wav")).await,
            game_over: decode(include_bytes!("../assets/game_over.wav")).await,
            music_menu: decode(include_bytes!("../assets/music_menu.wav")).await,
            music_game: decode(include_bytes!("../assets/music_game.wav")).await,

            playing: None,
            muted: false,
            pops_this_frame: 0,
            shoot_cooldown: 0.0,
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Reset the per-frame throttles. Call once at the top of every frame.
    // ─────────────────────────────────────────────────────────────────────────
    pub fn begin_frame(&mut self, dt: f32) {
        self.pops_this_frame = 0;
        if self.shoot_cooldown > 0.0 {
            self.shoot_cooldown -= dt;
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // A fruit burst. `tier` picks the pitch — smaller fruit pop higher.
    // Silently dropped once the per-frame budget is spent.
    // ─────────────────────────────────────────────────────────────────────────
    pub fn play_pop(&mut self, tier: u8) {
        if self.pops_this_frame >= MAX_POPS_PER_FRAME {
            return;
        }
        self.pops_this_frame += 1;

        // Duck each successive pop so simultaneous bursts don't spike the mix.
        let duck = 1.0 - POP_DUCK_PER_EXTRA * (self.pops_this_frame - 1) as f32;
        let index = (tier as usize).min(self.pops.len() - 1);
        self.sfx(&self.pops[index], POP_VOLUME * duck.max(0.25));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // A tower firing. Rate-limited across all towers at once.
    // ─────────────────────────────────────────────────────────────────────────
    pub fn play_shoot(&mut self) {
        if self.shoot_cooldown > 0.0 {
            return;
        }
        self.shoot_cooldown = SHOOT_MIN_GAP;
        self.sfx(&self.shoot, SHOOT_VOLUME);
    }

    pub fn play_splash(&self) {
        self.sfx(&self.splash, SPLASH_VOLUME);
    }

    pub fn play_freeze(&self) {
        self.sfx(&self.freeze, FREEZE_VOLUME);
    }

    pub fn play_place(&self) {
        self.sfx(&self.place, PLACE_VOLUME);
    }

    pub fn play_deny(&self) {
        self.sfx(&self.deny, DENY_VOLUME);
    }

    pub fn play_upgrade(&self) {
        self.sfx(&self.upgrade, UPGRADE_VOLUME);
    }

    pub fn play_sell(&self) {
        self.sfx(&self.sell, SELL_VOLUME);
    }

    pub fn play_leak(&self) {
        self.sfx(&self.leak, LEAK_VOLUME);
    }

    pub fn play_wave_start(&self) {
        self.sfx(&self.wave_start, WAVE_START_VOLUME);
    }

    pub fn play_wave_clear(&self) {
        self.sfx(&self.wave_clear, WAVE_CLEAR_VOLUME);
    }

    pub fn play_game_over(&self) {
        self.sfx(&self.game_over, GAME_OVER_VOLUME);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Switch to a music loop. Re-requesting the current track does nothing, so
    // this is safe to call every frame.
    // ─────────────────────────────────────────────────────────────────────────
    pub fn play_music(&mut self, track: Track) {
        if self.playing == Some(track) {
            return;
        }

        self.stop_music();
        self.playing = Some(track);

        if !self.muted {
            play_sound(
                self.track_sound(track),
                PlaySoundParams {
                    looped: true,
                    volume: MUSIC_VOLUME,
                },
            );
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Mute or unmute everything. Music resumes from the top when unmuted, since
    // macroquad gives no way to seek a playing sound.
    // ─────────────────────────────────────────────────────────────────────────
    pub fn toggle_mute(&mut self) {
        self.muted = !self.muted;

        if let Some(track) = self.playing {
            if self.muted {
                stop_sound(self.track_sound(track));
            } else {
                play_sound(
                    self.track_sound(track),
                    PlaySoundParams {
                        looped: true,
                        volume: MUSIC_VOLUME,
                    },
                );
            }
        }
    }

    pub fn muted(&self) -> bool {
        self.muted
    }

    fn stop_music(&mut self) {
        if let Some(track) = self.playing {
            stop_sound(self.track_sound(track));
        }
        self.playing = None;
    }

    fn track_sound(&self, track: Track) -> &Sound {
        match track {
            Track::Menu => &self.music_menu,
            Track::Game => &self.music_game,
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Fire off a one-shot effect, unless the player has muted the game.
    // ─────────────────────────────────────────────────────────────────────────
    fn sfx(&self, sound: &Sound, volume: f32) {
        if self.muted {
            return;
        }
        play_sound(
            sound,
            PlaySoundParams {
                looped: false,
                volume,
            },
        );
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Decode one embedded WAV. A failure here means the binary itself is corrupt,
// so there is nothing sensible to fall back to.
// ─────────────────────────────────────────────────────────────────────────────
async fn decode(bytes: &[u8]) -> Sound {
    load_sound_from_bytes(bytes)
        .await
        .expect("embedded audio asset failed to decode")
}
